# Generated by Django 5.2.9 on 2026-02-15 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='CodeBuddy', max_length=50)),
                ('stage', models.CharField(choices=[('spark', 'Spark'), ('flicker', 'Flicker'), ('flame', 'Flame'), ('blaze', 'Blaze'), ('nova', 'Nova')], default='spark', max_length=10)),
                ('commits_today', models.IntegerField(default=0)),
                ('commits_this_week', models.IntegerField(default=0)),
                ('total_commits', models.IntegerField(default=0)),
                ('mood', models.CharField(default='happy', max_length=20)),
                ('last_fed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
