# Generated by Django 5.2.9 on 2026-02-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digitalpet',
            options={'verbose_name': 'Digital Pet'},
        ),
        migrations.AddField(
            model_name='digitalpet',
            name='commit_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='digitalpet',
            name='coverage_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='digitalpet',
            name='hunger',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='digitalpet',
            name='last_commit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalpet',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalpet',
            name='login_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='digitalpet',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='digitalpet',
            name='last_fed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='digitalpet',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('content', 'Content'), ('tired', 'Tired'), ('sad', 'Sad'), ('starving', 'Starving')], default='happy', max_length=20),
        ),
        migrations.AlterField(
            model_name='digitalpet',
            name='stage',
            field=models.CharField(choices=[('ember', 'Ember'), ('spark', 'Spark'), ('flicker', 'Flicker'), ('flame', 'Flame'), ('blaze', 'Blaze'), ('nova', 'Nova')], default='spark', max_length=20),
        ),
    ]
