# Generated by Django 5.2.9 on 2026-01-15 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE ToDo_items AUTO_INCREMENT = 5000000000;"),
    ]
