# Generated by Django 5.2.9 on 2026-01-15 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0002_auto_20260114_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='lists',
            options={'verbose_name': 'List', 'verbose_name_plural': 'Lists'},
        ),
    ]
