# Generated by Django 5.2.9 on 2026-01-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0003_alter_items_options_alter_lists_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='lists', to='ToDo.items'),
        ),
    ]
