# Generated by Django 5.2.9 on 2026-01-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0004_lists_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='version',
            field=models.CharField(default='v1.0', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='items',
            unique_together={('title', 'version')},
        ),
    ]
