# Generated by Django 5.2.9 on 2026-01-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0005_items_attachment_alter_items_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='attachment',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
