# Generated by Django 5.2.9 on 2026-01-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0006_alter_items_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='payload',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='typeflag',
            field=models.CharField(choices=[('CHECKMARK', 'Checkmark'), ('RADIO', 'Radio Buttons'), ('MULTICHOICE', 'Multi-Choice'), ('HYPERLINK', 'Hyperlink')], default='CHECKMARK', max_length=20),
        ),
    ]
