# Generated by Django 5.2.9 on 2026-01-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0007_items_payload_items_status_items_typeflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('UNKNOWN', 'Unknown'), ('COMPLETE', 'Complete'), ('INCOMPLETE', 'Incomplete'), ('POSTPONED', 'Postponed'), ('DROPPED', 'Dropped'), ('PARTIALLY_COMPLETE', 'Partially Complete')], default='ACTIVE', max_length=20),
        ),
    ]
