# Generated by Django 5.2.9 on 2026-01-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0008_alter_items_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='payload',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
