# Generated by Django 5.2.9 on 2026-01-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0009_alter_items_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='created_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
