# Generated by Django 5.2.9 on 2026-01-22 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0011_items_created_by'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lists',
            options={'ordering': ['title'], 'verbose_name': 'List', 'verbose_name_plural': 'Lists'},
        ),
        migrations.AlterUniqueTogether(
            name='items',
            unique_together={('title', 'version', 'created_by')},
        ),
        migrations.AddField(
            model_name='items',
            name='expiryAbsolute',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='expiryInterval',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='markstyle',
            field=models.CharField(choices=[('user', 'User Scope'), ('timeUSER', 'Time Limits Scope'), ('timeLIST', 'Time Limits Scope'), ('thelist', 'List Scope'), ('theitem', 'Item Scope')], default='theitem', max_length=10),
        ),
        migrations.AddField(
            model_name='items',
            name='short_title',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='sublist',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='visibility_allowed_groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
        migrations.AddField(
            model_name='lists',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lists',
            name='short_title',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='lists',
            name='visibility_allowed_groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='items',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Markers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markervalue', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('markerDateTime', models.DateTimeField(auto_now=True)),
                ('markerStartTime', models.DateTimeField(auto_now=True)),
                ('item_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_markers', to='ToDo.items')),
                ('list_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_markers', to='ToDo.lists')),
                ('user_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_markers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marker',
                'verbose_name_plural': 'Markers',
            },
        ),
        migrations.RemoveField(
            model_name='items',
            name='created_user',
        ),
    ]
