# Generated by Django 5.2.9 on 2026-01-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0012_alter_lists_options_alter_items_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markers',
            name='markerDateTime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='markers',
            name='markerStartTime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
