# Generated by Django 5.2.9 on 2026-01-20 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('Read Only', 'Can only read Lists and Items'), ('view_my_profile', 'Can view my profile')]},
        ),
    ]
