# Generated by Django 5.2.9 on 2026-01-20 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('view_my_profile', 'Can view my profile'), ('edit_my_profile', 'Can edit my profile')]},
        ),
    ]
