# Generated by Django 5.2.9 on 2026-01-24 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_title', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('version', models.CharField(default='v1.0', max_length=30)),
                ('attachment', models.BinaryField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('UNKNOWN', 'Unknown'), ('COMPLETE', 'Complete'), ('INCOMPLETE', 'Incomplete'), ('POSTPONED', 'Postponed'), ('DROPPED', 'Dropped'), ('PARTIALLY_COMPLETE', 'Partially Complete')], default='ACTIVE', max_length=20)),
                ('typeflag', models.CharField(choices=[('CHECKMARK', 'Checkmark'), ('RADIO', 'Radio Buttons'), ('MULTICHOICE', 'Multi-Choice'), ('HYPERLINK', 'Hyperlink')], default='CHECKMARK', max_length=20)),
                ('markstyle', models.CharField(choices=[('user', 'User Scope'), ('timeUSER', 'Time Limits Scope'), ('timeLIST', 'Time Limits Scope'), ('thelist', 'List Scope'), ('theitem', 'Item Scope')], default='theitem', max_length=10)),
                ('sublist', models.BigIntegerField(blank=True, default=None, null=True)),
                ('expiryInterval', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('expiryAbsolute', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visibility_allowed_groups', models.ManyToManyField(blank=True, to='auth.group')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'unique_together': {('title', 'version', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_title', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(blank=True, related_name='lists', to='app_ToDo.items')),
                ('visibility_allowed_groups', models.ManyToManyField(blank=True, to='auth.group')),
            ],
            options={
                'verbose_name': 'List',
                'verbose_name_plural': 'Lists',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Markers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markervalue', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('markerDateTime', models.DateTimeField(blank=True, default=None, null=True)),
                ('markerStartTime', models.DateTimeField(blank=True, default=None, null=True)),
                ('item_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_markers', to='app_ToDo.items')),
                ('list_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_markers', to='app_ToDo.lists')),
                ('user_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_markers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marker',
                'verbose_name_plural': 'Markers',
            },
        ),
    ]
