# Generated by Django 5.2.9 on 2026-01-24 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ToDo', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markers',
            name='item_obj',
        ),
        migrations.RemoveField(
            model_name='lists',
            name='items',
        ),
        migrations.RemoveField(
            model_name='lists',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='lists',
            name='visibility_allowed_groups',
        ),
        migrations.RemoveField(
            model_name='markers',
            name='list_obj',
        ),
        migrations.RemoveField(
            model_name='markers',
            name='user_obj',
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=25)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app_ToDo.node')),
                ('user_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_markers', to=settings.AUTH_USER_MODEL)),
                ('visibility_allowed_groups', models.ManyToManyField(blank=True, to='auth.group')),
            ],
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='Lists',
        ),
        migrations.DeleteModel(
            name='Markers',
        ),
    ]
