# Generated by Django 5.2.9 on 2026-01-27 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0003_alter_profile_created_at_alter_profile_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('view_my_profile', 'Can view own profile'), ('edit_my_profile', 'Can edit own profile')]},
        ),
    ]
