# Generated by Django 5.2.9 on 2026-02-08 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0005_remove_profile_avatar_profile_avatar_blob_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
        ),
    ]
