# Generated by Django 5.2.9 on 2026-02-15 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0006_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('view_own_profile', 'Can view own profile'), ('edit_own_profile', 'Can edit own profile')]},
        ),
    ]
