# Generated by Django 5.2.9 on 2026-02-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0008_remove_old_profile_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_username',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
