#!/usr/bin/env python3
# -*- coding: utf-8 -*-
###############################################################################
r"""
core.py
MikesLists.settings.core
/srv/django/MikesLists_dev/MikesLists/settings/core.py


"""
__version__ = "0.0.0.000095-dev"
__author__ = "Mike Merrett"
__updated__ = "2026-01-19 17:04:21"
###############################################################################


"""
Django settings for MikesLists project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


import os
from pathlib import Path
from decouple import config

import accounts
import ToDo


def ready():
    accounts.assign_permissions()

    try:
        accounts.assign_permissions()
    except Exception as e:
        print(f"Error during ready(): {e}")


def accounts_post_configure_signal(sender, **kwargs):
    ready()


ADMINS = [
    ("Mike", "mmerrett@merrett.ca"),
    ("pi", "admin@merrett.ca"),
]

# move allowed hosts to the core
#   - it will be the same for dev and test
#   -- live will probably add something like any hosts
ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "localhost.local",
    "pidj",
    "pidj.local",
    "10.0.0.9",
    "pi9.local",
    "10.0.0.208",
    "AlienMike.local",
    "AlienMike",
    "10.0.0.100",
]

# extra_host = os.getenv("EXTRA_ALLOWED_HOSTS")
extra_host = config("EXTRA_ALLOWED_HOSTS", default="")
if extra_host:
    ALLOWED_HOSTS.append(extra_host)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parents[2]

# ENV_NAME = os.getenv("ENV_NAME")
ENV_NAME = config("ENV_NAME")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# Application definition
ROOT_URLCONF = "MikesLists.urls"

WSGI_APPLICATION = "MikesLists.wsgi.application"
# RUNSERVERPLUS_SERVER_ADDRESS_PORT = "0.0.0.0:8000"

# Where to go after logging in
LOGIN_REDIRECT_URL = "/"  # Use the 'name' of your list index view

# Where to go after logging out
LOGOUT_REDIRECT_URL = "login"

# The URL for the login page
LOGIN_URL = "login"


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "reversion",
    "accounts",
    "ToDo",
    "widget_tweaks",
    "django_extensions",
]

# path('todo/', include('ToDo.urls'))

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "MikesLists.context_processors.export_env_vars",
                # 'MikesLists.context_processors.env_name',
            ],
        },
    },
]


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE": config("DB_ENGINE"),
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT", default="3306"),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
        "TEST": {
            "NAME": f"test_{config('DB_NAME')}",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = "en-us"
# TIME_ZONE = 'UTC'
TIME_ZONE = "America/Toronto"
# TIME_ZONE = 'America/Whitehorse'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles_collected"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = "mail.merrett.ca"  # or your provider
EMAIL_PORT = 465  # 465 for SSL
# EMAIL_USE_TLS = True
EMAIL_USE_SSL = True
EMAIL_HOST_USER = "public@merrett.ca"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
